### ISSUE TITLE
iitc plugin configuration example needed

### ISSUE THREAD

**Issue by TontonPhil** [jonthekiller/LocationHistoryIngress#1]
could someone show an example of the iitc script configuration 

I've customized my script this way :
  var osm = L.tileLayer.wms('http://localhost:8080/geoserver/', {
    layers: 'ingress:historiquedespositions',

but when looking into the geoserver logs with this iitc script configuration, it seems that the goeserver does not find how route to the correct service (that's my understanding of the geoserver logs)

thanks.

**Comment by jonthekiller** [comment]
Your URL should be more like this "http://localhost:8080/geoserver/wms?"
